name: computed_flutter
description: Straightforward, reliable, performant and testable reactive state management for Flutter

repository: https://github.com/mstniy/computed_flutter

version: 0.0.1

environment:
  sdk: ">=2.17.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  built_collection: ^5.1.1
  computed: ^0.3.0
  #computed:
  #  path: ../computed
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  test: ^1.24.3
