name: computed_flutter
description: Straightforward, reliable, performant and testable reactive state management for Flutter

repository: https://github.com/mstniy/computed_flutter

version: 0.1.0

environment:
  sdk: ">=2.17.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  computed: ^0.3.2
  #computed:
  #  path: ../computed
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  test: ^1.24.3

flutter:
  uses-material-design: true
