name: tests

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  check:
    strategy:
      matrix:
        flutter_version: [3.29.x, 3.27.x]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ matrix.flutter_version }}
          channel: "stable"

      - name: Install dependencies
        run: |
          flutter pub get

      - name: Verify formatting
        run: dart format --output=none --set-exit-if-changed .

      - name: Analyze source
        run: flutter analyze

      - name: Run tests
        run: flutter test --coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage/lcov.info
          token: ${{ secrets.CODECOV_TOKEN }}
